# Generated by Django 5.2.8 on 2025-12-02 21:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoldPriceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lock_duration_seconds", models.IntegerField(default=60)),
                (
                    "safeguard_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Percentage added before spread margin.",
                        max_digits=5,
                    ),
                ),
                (
                    "spread_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="Percentage added after safeguard margin.",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoldPriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("usd_per_ounce", models.DecimalField(decimal_places=4, max_digits=14)),
                ("usd_pkr_rate", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "pkr_per_ounce_raw",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "pkr_per_gram_raw",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "pkr_per_tola_raw",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "pkr_per_ounce_final",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "pkr_per_gram_final",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "pkr_per_tola_final",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyClosingPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("closing_ounce", models.DecimalField(decimal_places=4, max_digits=14)),
                ("closing_gram", models.DecimalField(decimal_places=4, max_digits=14)),
                ("closing_tola", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.goldpricesnapshot",
                    ),
                ),
            ],
        ),
    ]
