# Generated by Django 5.2.8 on 2025-12-01 12:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoldPriceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="default", max_length=50, unique=True),
                ),
                (
                    "safety_margin_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Safeguard % added to spot PKR price before setting internal for-sale price.",
                        max_digits=5,
                    ),
                ),
                (
                    "buy_spread_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="Additional % charged when a user BUYS gold (on top of internal for-sale price).",
                        max_digits=5,
                    ),
                ),
                (
                    "gram_per_tola",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("11.6638"),
                        help_text="Number of grams in one tola.",
                        max_digits=8,
                    ),
                ),
                (
                    "ounce_to_gram",
                    models.DecimalField(
                        decimal_places=7,
                        default=Decimal("31.1034768"),
                        help_text="Number of grams in one troy ounce.",
                        max_digits=10,
                    ),
                ),
                (
                    "last_spot_ounce_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "last_usd_pkr",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("last_computed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cache_ttl_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="How long (in seconds) to reuse cached FX & spot prices before refetching.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gold Price Config",
                "verbose_name_plural": "Gold Price Config",
            },
        ),
    ]
