# Generated by Django 5.2.8 on 2025-12-11 18:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldpriceconfig",
            name="min_buy_amount_pkr",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("500.00"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="goldpriceconfig",
            name="lock_duration_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
