# Generated by Django 5.2.8 on 2025-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldPriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spot_ounce_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Spot price of 1 oz Gold in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "usd_pkr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="USD to PKR exchange rate",
                        max_digits=10,
                    ),
                ),
                (
                    "spot_ounce_pkr",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("spot_gram_pkr", models.DecimalField(decimal_places=2, max_digits=14)),
                ("spot_tola_pkr", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "safeguarded_ounce_pkr",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "safeguarded_gram_pkr",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "safeguarded_tola_pkr",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("buy_ounce_pkr", models.DecimalField(decimal_places=2, max_digits=14)),
                ("buy_gram_pkr", models.DecimalField(decimal_places=2, max_digits=14)),
                ("buy_tola_pkr", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
