# Generated by Django 5.2.8 on 2025-12-02 09:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_goldpricesnapshot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goldpriceconfig",
            options={},
        ),
        migrations.AlterModelOptions(
            name="goldpricesnapshot",
            options={},
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="buy_spread_pct",
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="cache_ttl_seconds",
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="gram_per_tola",
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="last_computed_at",
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="last_spot_ounce_usd",
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="last_usd_pkr",
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="name",
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="ounce_to_gram",
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="safety_margin_pct",
        ),
        migrations.RemoveField(
            model_name="goldpriceconfig",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="buy_gram_pkr",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="buy_ounce_pkr",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="buy_tola_pkr",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="safeguarded_gram_pkr",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="safeguarded_ounce_pkr",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="safeguarded_tola_pkr",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="spot_gram_pkr",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="spot_ounce_pkr",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="spot_ounce_usd",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="spot_tola_pkr",
        ),
        migrations.RemoveField(
            model_name="goldpricesnapshot",
            name="usd_pkr",
        ),
        migrations.AddField(
            model_name="goldpriceconfig",
            name="safeguard_margin",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("2.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="goldpriceconfig",
            name="spread_margin",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("3.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="goldpricesnapshot",
            name="pkr_per_gram_final",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="goldpricesnapshot",
            name="pkr_per_gram_raw",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="goldpricesnapshot",
            name="pkr_per_ounce_final",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="goldpricesnapshot",
            name="pkr_per_ounce_raw",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="goldpricesnapshot",
            name="pkr_per_tola_final",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="goldpricesnapshot",
            name="pkr_per_tola_raw",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="goldpricesnapshot",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goldpricesnapshot",
            name="usd_per_ounce",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="goldpricesnapshot",
            name="usd_pkr_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
    ]
