# Generated by Django 5.2.8 on 2025-12-13 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_goldpriceconfig_min_buy_amount_pkr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldpriceconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goldpriceconfig",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Only one GoldPriceConfig should be active at a time.",
            ),
        ),
        migrations.AddField(
            model_name="goldpriceconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
