# Generated by Django 5.2.8 on 2025-12-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_goldpriceconfig_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyClosingPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("closing_ounce", models.DecimalField(decimal_places=4, max_digits=14)),
                ("closing_gram", models.DecimalField(decimal_places=4, max_digits=14)),
                ("closing_tola", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.goldpricesnapshot",
                    ),
                ),
            ],
        ),
    ]
