# Generated by Django 5.2.8 on 2025-12-13 13:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "market",
            "0003_goldpriceconfig_created_at_goldpriceconfig_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="goldpriceconfig",
            name="buy_fee_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("3.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="goldpriceconfig",
            name="sell_fee_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="dailyclosingprice",
            name="source_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.goldpricesnapshot",
            ),
        ),
        migrations.AlterField(
            model_name="goldpriceconfig",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="goldpricesnapshot",
            name="pkr_per_gram_final",
            field=models.DecimalField(decimal_places=4, default=39000, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goldpricesnapshot",
            name="pkr_per_gram_raw",
            field=models.DecimalField(decimal_places=4, default=39000, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goldpricesnapshot",
            name="pkr_per_ounce_final",
            field=models.DecimalField(decimal_places=4, default=39000, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goldpricesnapshot",
            name="pkr_per_ounce_raw",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goldpricesnapshot",
            name="pkr_per_tola_final",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goldpricesnapshot",
            name="pkr_per_tola_raw",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
