# Generated by Django 5.2.8 on 2025-12-02 21:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_balance_grams",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.0"), max_digits=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_quantity_grams",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "locked_price_per_gram",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("total_pkr", models.DecimalField(decimal_places=2, max_digits=20)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order_token",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_LOCKED", "Pending Locked"),
                            ("EXECUTED", "Executed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING_LOCKED",
                        max_length=20,
                    ),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "snapshot_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.goldpricesnapshot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_quantity_grams",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "locked_price_per_gram",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("total_pkr", models.DecimalField(decimal_places=2, max_digits=20)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order_token",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_LOCKED", "Pending Locked"),
                            ("EXECUTED", "Executed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING_LOCKED",
                        max_length=20,
                    ),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "snapshot_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.goldpricesnapshot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")], max_length=6
                    ),
                ),
                (
                    "gold_amount_grams",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "balance_after_tx",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallet.wallet"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
