# Generated by Django 5.2.8 on 2025-11-19 10:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_balance",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Total gold held by the user (in grams, 8 decimal precision).",
                        max_digits=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy Gold"),
                            ("SELL", "Sell Gold"),
                            ("ADJUST", "Admin Adjustment"),
                            ("REFERRAL", "Referral Gold Credit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gold_delta",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Change in gold quantity. Positive for buy/credit, negative for sell/debit.",
                        max_digits=20,
                    ),
                ),
                (
                    "gold_balance_after",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Gold balance after applying this ledger entry.",
                        max_digits=20,
                    ),
                ),
                (
                    "fiat_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fiat value (e.g. PKR) of this operation, for audit only.",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "fiat_currency",
                    models.CharField(
                        default="PKR",
                        help_text="ISO currency code, e.g. PKR.",
                        max_length=3,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
