# Generated by Django 5.2.8 on 2025-11-20 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="gold_balance_after",
            field=models.DecimalField(
                decimal_places=8,
                help_text="Gold balance after applying this ledger entry (in grams).",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="gold_delta",
            field=models.DecimalField(
                decimal_places=8,
                help_text="Change in gold quantity. Positive for buy/credit, negative for sell/debit (in grams).",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
