# Generated by Django 5.2.8 on 2025-12-11 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_orderauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_grams",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "reserved_grams",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="buyorder",
            name="total_pkr",
        ),
        migrations.RemoveField(
            model_name="sellorder",
            name="total_pkr",
        ),
        migrations.AddField(
            model_name="buyorder",
            name="fee_pkr",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="buyorder",
            name="soft_allocated_grams",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="buyorder",
            name="total_payable_pkr",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="sellorder",
            name="fee_pkr",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="sellorder",
            name="soft_allocated_grams",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="sellorder",
            name="total_payable_pkr",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="buyorder",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 11, 18, 5, 12, 881714, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="buyorder",
            name="locked_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 11, 18, 5, 24, 144710, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="buyorder",
            name="locked_price_per_gram",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="buyorder",
            name="order_token",
            field=models.CharField(default="temp-token", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sellorder",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 11, 18, 5, 44, 25392, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sellorder",
            name="locked_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 11, 18, 5, 48, 894651, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sellorder",
            name="locked_price_per_gram",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="sellorder",
            name="order_token",
            field=models.CharField(default="temp-token", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
